"""add created_at and updated_at indexes to articles

Revision ID: 4cbaaf9285fb
Revises: a79b3ff73cf9
Create Date: 2026-01-28 12:55:01.894676

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4cbaaf9285fb"
down_revision: str | Sequence[str] | None = "a79b3ff73cf9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index("ix_articles_created_at", ["created_at"], unique=False)
        batch_op.create_index("ix_articles_updated_at", ["updated_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index("ix_articles_updated_at")
        batch_op.drop_index("ix_articles_created_at")

    # ### end Alembic commands ###
