"""create articles table

Revision ID: a79b3ff73cf9
Revises: bcd78a54e570
Create Date: 2026-01-26 13:28:12.272837

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a79b3ff73cf9"
down_revision: str | Sequence[str] | None = "bcd78a54e570"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("headline", sa.String(length=1024), nullable=False),
        sa.Column("description", sa.String(length=4096), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_seen_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.create_index(
            "ix_articles_last_seen_at", ["last_seen_at"], unique=False
        )
        batch_op.create_index("ix_articles_source_id", ["source_id"], unique=False)
        batch_op.create_index("ix_articles_url", ["url"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("articles", schema=None) as batch_op:
        batch_op.drop_index("ix_articles_url")
        batch_op.drop_index("ix_articles_source_id")
        batch_op.drop_index("ix_articles_last_seen_at")

    op.drop_table("articles")
    # ### end Alembic commands ###
